baseURL = 'htps://driverevive.com.au'
languageCode = 'en-us'
title = 'Rich told me to blog'
theme = 'not-much'
copyright = "take what you need Â© {year}"
followSymlinks = true

# Navigation
[menu]
  [[menu.main]]
    identifier = "home"
    name = "home"
    title = "Home"
    url = "/"
    weight = 1
  
[[menu.main]]
    identifier = "lab"
    name = "lab"
    title = "lab"
    url = "/lab"
    weight = 2

[[menu.main]]
    identifier = "offsec"
    name = "offsec"
    title = "offsec"
    url = "/offsec"
    weight = 3

  [[menu.main]]
    name = "windows"
    parent = "offsec"
    url = "/offsec/windows"
    weight = 1

  [[menu.main]]
    name = "linux"
    parent = "offsec"
    url = "/offsec/linux"
    weight = 2

[[menu.main]]
    identifier = "dvwa"
    name = "dvwa"
    title = "dvwa"
    url = "/dvwa"
    weight = 6

[[menu.main]]
    identifier = "owasp-shop"
    name = "owasp-shop"
    title = "owasp-shop"
    url = "/owasp-shop"
    weight = 4

[[menu.main]]
    identifier = "portswigger"
    name = "portswigger"
    title = "portswigger"
    url = "/portswigger"
    weight = 5

[[menu.main]]
    identifier = "about"
    name = "about"
    title = "About"
    url = "/about"
    weight = 7
  
[[menu.main]]
    identifier = "github"
    name = "github"
    title = "GitHub"
    url = "https://github.com/Nautilloid"
    weight = 8

paginate = 50

[markup]
  [markup.highlight]
    style = 'dracula'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]
theme = "dark"
palette = "catpuccin"
showThemeNotice = true
showPostsSummary = true
summaryLength = 150


[taxonomies]
  category = "categories"
  tag = "tags"

[sections]
  posts = "lab"

